### ISSUE TITLE
Cannot connect due to StarScream compression issue

### ISSUE THREAD

**Issue by Nerkyator** [home-assistant/HAKit#45]
HAKit cannot connect to HA instance due to [this](https://github.com/daltoniam/Starscream/issues/743#issue-575306711) StarScream issue 

EDIT: [Forked project ](https://github.com/Nerkyator/HAKit)to fix the issue. I'm removing StarScream and reimplementing websocket connection natively. Will make a PR when ready (it is now working but lacks authentication layer & tests)

**Comment by Nerkyator** [comment]
@bgoncal I think this issue can be closed too as it seems resolved in `0.4.1` release :)

**Comment by bgoncal** [comment]
Thanks for letting me know
