### ISSUE TITLE
Doesn't compile on Linux due to Starscream

### ISSUE THREAD

**Issue by Cyberbeni** [home-assistant/HAKit#66]
I'm planning on writing a small utility tool for myself in Swift, which would run inside a Docker container. Starscream doesn't compile because it can't import zlib.

**Comment by bgoncal** [comment]
The goal of this repo is to be an interface between HA and Apple platforms, Starscream is a dependency we use to handle websocket and to remove/replace it will be a lot of work, feel free to give it a try but unfortunately for now thats the state we are.
